### ISSUE TITLE
remove dynpkg support

### ISSUE THREAD

**Issue by tkittel** [mctools/dgcode#41]
It is not useful for anything, and we get annoying stuff like (fixed by `dgbuild -c`):
```
dgbuild: ----begin traceback---
Traceback (most recent call last):
  File "/home/tkittel/work/dgcode_framework/.system/pypath/ess_dgbuild_internals/frontend.py", line 549, in dgbuild_main
    pkgloader = backend.perform_configuration(cmakeargs=cmakeargs,
  File "/home/tkittel/work/dgcode_framework/.system/pypath/ess_dgbuild_internals/backend.py", line 243, in perform_configuration
    mt = max(mt,dynpkgbuilder.get_mtime_deps())
  File "/home/tkittel/work/dgcode_framework/.system/pypath/ess_dgbuild_internals/dynpkg.py", line 121, in get_mtime_deps
    return mtime.mtime_pathlist(self.get_deppaths())
  File "/home/tkittel/work/dgcode_framework/.system/pypath/ess_dgbuild_internals/dynpkg.py", line 114, in get_deppaths
    self._loadmod()
  File "/home/tkittel/work/dgcode_framework/.system/pypath/ess_dgbuild_internals/dynpkg.py", line 92, in _loadmod
    assert len(sys.argv)==1
AssertionError
dgbuild: ----end traceback---
```

**Comment by tkittel** [comment]
done
